// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initEmulator() =>
    RustLib.instance.api.crateApiEmulatorInitEmulator();

Future<void> loadGame({required String jarPath}) =>
    RustLib.instance.api.crateApiEmulatorLoadGame(jarPath: jarPath);

Future<void> startGame() => RustLib.instance.api.crateApiEmulatorStartGame();

Future<void> pauseGame() => RustLib.instance.api.crateApiEmulatorPauseGame();

Future<void> resumeGame() => RustLib.instance.api.crateApiEmulatorResumeGame();

Future<void> stopGame() => RustLib.instance.api.crateApiEmulatorStopGame();

Future<int> getScreenWidth() =>
    RustLib.instance.api.crateApiEmulatorGetScreenWidth();

Future<int> getScreenHeight() =>
    RustLib.instance.api.crateApiEmulatorGetScreenHeight();

Future<Uint32List> getScreenPixels() =>
    RustLib.instance.api.crateApiEmulatorGetScreenPixels();

Future<void> sendKeyEvent({required int keyCode, required bool pressed}) =>
    RustLib.instance.api.crateApiEmulatorSendKeyEvent(
      keyCode: keyCode,
      pressed: pressed,
    );

Future<String?> getNextAudioEvent() =>
    RustLib.instance.api.crateApiEmulatorGetNextAudioEvent();

Future<String> installMod({required String zipPath}) =>
    RustLib.instance.api.crateApiEmulatorInstallMod(zipPath: zipPath);

Future<void> toggleMod({required String id, required bool enable}) =>
    RustLib.instance.api.crateApiEmulatorToggleMod(id: id, enable: enable);

Future<void> saveState({required String filepath}) =>
    RustLib.instance.api.crateApiEmulatorSaveState(filepath: filepath);

Future<void> loadState({required String filepath}) =>
    RustLib.instance.api.crateApiEmulatorLoadState(filepath: filepath);
